# calculate the mean and standard deviation of multiple csv files

In [27]:
import numpy as np
import os
import pandas as pd

## find your csv

In [28]:
def find_the_way(path,file_format):
    files_add = []
    # r=root, d=directories, f = files
    for r, d, f in os.walk(path):
        for file in f:
            if file_format in file:
                files_add.append(os.path.join(r, file))  
    return files_add
name_list=find_the_way('./csvs/','.csv')
name_list

['./csvs/file 1.csv',
 './csvs/file 10.csv',
 './csvs/file 2.csv',
 './csvs/file 3.csv',
 './csvs/file 4.csv',
 './csvs/file 5.csv',
 './csvs/file 6.csv',
 './csvs/file 7.csv',
 './csvs/file 8.csv',
 './csvs/file 9.csv']

## standard deviation

In [29]:
flag=1
for i in name_list:
    df = pd.read_csv(i) 
    col=i[7:-4]
    temp=pd.DataFrame(df.std(),columns=[col])
    if flag:
        std=temp
        flag=0
    else:
        std[col]=temp[col]

In [30]:
std

,file 1,file 10,file 2,file 3,file 4,file 5,file 6,file 7,file 8,file 9
Feature 1,30.802812,30.802812,30.802812,30.802812,30.802812,30.802812,30.802812,30.802812,30.802812,30.802812
Feature 2,29.263664,29.263664,29.263664,29.263664,29.263664,29.263664,29.263664,29.263664,29.263664,29.263664
Feature 3,29.482162,29.482162,29.482162,29.482162,29.482162,29.482162,29.482162,29.482162,29.482162,29.482162
Feature 4,27.375798,27.375798,27.375798,27.375798,27.375798,27.375798,27.375798,27.375798,27.375798,27.375798
Feature 5,29.116318,29.116318,29.116318,29.116318,29.116318,29.116318,29.116318,29.116318,29.116318,29.116318
Feature 6,29.296001,29.296001,29.296001,29.296001,29.296001,29.296001,29.296001,29.296001,29.296001,29.296001
Feature 7,30.024251,30.024251,30.024251,30.024251,30.024251,30.024251,30.024251,30.024251,30.024251,30.024251
Feature 8,30.522858,30.522858,30.522858,30.522858,30.522858,30.522858,30.522858,30.522858,30.522858,30.522858
Feature 9,28.809202,28.809202,28.809202,28.809202,28.809202,28.809202,28.809202,28.809202,28.809202,28.809202
Feature 10,30.759307,30.759307,30.759307,30.759307,30.759307,30.759307,30.759307,30.759307,30.759307,30.759307
Feature 11,29.139045,29.139045,29.139045,29.139045,29.139045,29.139045,29.139045,29.139045,29.139045,29.139045
Feature 12,30.880310,30.880310,30.880310,30.880310,30.880310,30.880310,30.880310,30.880310,30.880310,30.880310
Feature 13,30.875787,30.875787,30.875787,30.875787,30.875787,30.875787,30.875787,30.875787,30.875787,30.875787
Feature 14,30.225982,30.225982,30.225982,30.225982,30.225982,30.225982,30.225982,30.225982,30.225982,30.225982

## take its transpose and save

In [31]:
std=std.T
std

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14
file 1,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 10,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 2,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 3,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 4,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 5,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 6,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 7,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 8,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982
file 9,30.802812,29.263664,29.482162,27.375798,29.116318,29.296001,30.024251,30.522858,28.809202,30.759307,29.139045,30.88031,30.875787,30.225982

In [32]:
std.to_csv("std.csv",index=None)
std=std.round(3)

# Mean

In [33]:
flag=1
for i in name_list:
    df = pd.read_csv(i) 
    col=i[7:-4]
    temp=pd.DataFrame(df.mean(),columns=[col])
    if flag:
        mean=temp
        flag=0
    else:
        mean[col]=temp[col]

In [34]:
mean

,file 1,file 10,file 2,file 3,file 4,file 5,file 6,file 7,file 8,file 9
Feature 1,44.07,44.07,44.07,44.07,44.07,44.07,44.07,44.07,44.07,44.07
Feature 2,53.04,53.04,53.04,53.04,53.04,53.04,53.04,53.04,53.04,53.04
Feature 3,48.29,48.29,48.29,48.29,48.29,48.29,48.29,48.29,48.29,48.29
Feature 4,44.80,44.80,44.80,44.80,44.80,44.80,44.80,44.80,44.80,44.80
Feature 5,41.76,41.76,41.76,41.76,41.76,41.76,41.76,41.76,41.76,41.76
Feature 6,50.87,50.87,50.87,50.87,50.87,50.87,50.87,50.87,50.87,50.87
Feature 7,48.83,48.83,48.83,48.83,48.83,48.83,48.83,48.83,48.83,48.83
Feature 8,56.46,56.46,56.46,56.46,56.46,56.46,56.46,56.46,56.46,56.46
Feature 9,51.36,51.36,51.36,51.36,51.36,51.36,51.36,51.36,51.36,51.36
Feature 10,49.92,49.92,49.92,49.92,49.92,49.92,49.92,49.92,49.92,49.92
Feature 11,50.87,50.87,50.87,50.87,50.87,50.87,50.87,50.87,50.87,50.87
Feature 12,49.32,49.32,49.32,49.32,49.32,49.32,49.32,49.32,49.32,49.32
Feature 13,48.67,48.67,48.67,48.67,48.67,48.67,48.67,48.67,48.67,48.67
Feature 14,50.19,50.19,50.19,50.19,50.19,50.19,50.19,50.19,50.19,50.19

## take its transpose and save

In [35]:
mean=mean.T
mean

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14
file 1,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 10,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 2,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 3,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 4,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 5,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 6,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 7,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 8,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19
file 9,44.07,53.04,48.29,44.8,41.76,50.87,48.83,56.46,51.36,49.92,50.87,49.32,48.67,50.19

##  merging columns

In [36]:
mean.to_csv("mean.csv",index=None)
mean=mean.round(3)

In [37]:
merged=pd.DataFrame()

In [42]:
for i in mean.columns:
    merged[i]=mean[i].astype(str)+"±"+std[i].astype(str)


merged

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,Feature 11,Feature 12,Feature 13,Feature 14
file 1,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 10,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 2,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 3,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 4,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 5,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 6,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 7,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 8,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226
file 9,44.07±30.803,53.04±29.264,48.29±29.482,44.8±27.376,41.76±29.116,50.87±29.296,48.83±30.024,56.46±30.523,51.36±28.809,49.92±30.759,50.87±29.139,49.32±30.88,48.67±30.876,50.19±30.226

In [43]:
merged.to_csv("merged.csv",index=None)